sudo: required
language: node_js
node_js:
  - "node"
  - "lts/*"
env:
  - VERSION_PJSIP=2.7.2 VERSION_LIBSRTP=2.1.0
addons:
  apt:
    packages:
      - wget
      - pkg-config
      - build-essential
      - python
      - gdb
before_install:
    - wget https://github.com/cisco/libsrtp/archive/v$VERSION_LIBSRTP.tar.gz
    - tar xzf v$VERSION_LIBSRTP.tar.gz
    - cd libsrtp-$VERSION_LIBSRTP
    - ./configure
    - make
    - sudo make install
    - sudo ldconfig
    - cd ..
    - wget -nv "http://www.pjsip.org/release/$VERSION_PJSIP/pjproject-$VERSION_PJSIP.tar.bz2" -O - | tar xjf -
    - cd pjproject-$VERSION_PJSIP
    - >
      ./configure
      --with-external-srtp
      --enable-shared
      --disable-sound
      --disable-oss
      --disable-sdl
      --disable-speex-aec
      --disable-video
      --disable-small-filter
      --disable-large-filter
      --disable-speex-aec
      --disable-l16-codec
      --disable-gsm-codec
      --disable-g722-codec
      --disable-g7221-codec
      --disable-speex-codec
      --disable-ilbc-codec
      --disable-opus
      > /dev/null
    - make dep all
    - sudo make install
    - sudo ldconfig
    - cd ..
install:
  - npm install
before_script:
  - ulimit -c unlimited
script: npm test
after_failure:
  - NODEJS=$(which node)
  - gdb -c ./core "$NODEJS" -ex "thread apply all bt" -ex "set pagination 0" -batch
